let report;
const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=v=>`${report.currency} ${Number(v).toLocaleString(undefined,{maximumFractionDigits:0})}`;
const num=v=>Number(v).toLocaleString();
const esc=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function filteredRows(){const st=$('#station-filter').value, pr=$('#product-filter').value, q=($('#search')?.value||'').toLowerCase().trim();return report.rows.filter(r=>(st==='all'||r.station===st)&&(pr==='all'||r.product===pr)&&(!q||Object.values(r).join(' ').toLowerCase().includes(q)));}
function group(rows,key){const m=new Map();for(const r of rows){const k=r[key];const x=m.get(k)||{label:k,qty:0,grossRevenue:0};x.qty+=r.qty;x.grossRevenue+=r.grossRevenue;m.set(k,x)}return [...m.values()].sort((a,b)=>b.grossRevenue-a.grossRevenue)}
function groupDate(rows){const m=new Map();for(const r of rows){const x=m.get(r.date)||{label:r.date,qty:0,grossRevenue:0};x.qty+=r.qty;x.grossRevenue+=r.grossRevenue;m.set(r.date,x)}return [...m.values()].sort((a,b)=>a.label.localeCompare(b.label))}
function renderRun(){ $('#run-card').innerHTML=`<dl><div><dt>Source workbook</dt><dd>Sales_Master_Consolidated_May26.xlsx</dd></div><div><dt>Period</dt><dd>${esc(report.period)}</dd></div><div><dt>Currency</dt><dd>${esc(report.currency)}</dd></div><div><dt>Scope</dt><dd>${report.metrics.stations} stations · ${report.metrics.products} product categories</dd></div><div><dt>Note</dt><dd>${esc(report.sourceNote)}</dd></div></dl>`;}
function renderCards(rows=report.rows){const rev=rows.reduce((s,r)=>s+r.grossRevenue,0), qty=rows.reduce((s,r)=>s+r.qty,0);const stations=new Set(rows.map(r=>r.station)).size, products=new Set(rows.map(r=>r.product)).size;const cards=[['Gross revenue',money(rev),`${num(qty)} units sold`],['Units sold',num(qty),`${stations} station(s) in filter`],['Avg revenue/unit',`${report.currency} ${(rev/(qty||1)).toFixed(2)}`,`${products} product category/categories`],['Data rows',num(rows.length),'Station/date/product aggregates']];$('#metric-cards').innerHTML=cards.map(c=>`<article class="metric-card"><div class="value">${esc(c[1])}</div><div class="label">${esc(c[0])}</div><div class="detail">${esc(c[2])}</div></article>`).join('');}
function renderInsights(){ $('#insight-grid').innerHTML=report.insights.map((t,i)=>`<article class="insight"><div class="num">${String(i+1).padStart(2,'0')}</div><p>${esc(t)}</p></article>`).join('');}
function barChart(el,data){const max=Math.max(...data.map(d=>d.grossRevenue),1);el.innerHTML=data.map(d=>`<div class="bar-row"><div class="bar-label" title="${esc(d.label)}">${esc(d.label)}</div><div class="bar-track"><div class="bar-fill" style="width:${Math.max(3,d.grossRevenue/max*100)}%"></div></div><div class="bar-value">${money(d.grossRevenue)}</div></div>`).join('')||'<p>No matching data.</p>';}
function dateChart(el,data){const max=Math.max(...data.map(d=>d.grossRevenue),1);el.innerHTML=`<div class="line-chart" style="--n:${Math.max(data.length,1)}">${data.map(d=>`<div class="line-bar" style="height:${Math.max(4,d.grossRevenue/max*100)}%"><span>${money(d.grossRevenue)}</span></div>`).join('')}</div><div class="line-labels" style="--n:${Math.max(data.length,1)}">${data.map(d=>`<div>${esc(d.label)}</div>`).join('')}</div>`;}
function renderMatrix(rows){const stations=[...new Set(rows.map(r=>r.station))].sort();const products=[...new Set(rows.map(r=>r.product))].sort();const m=new Map();let max=1;for(const r of rows){const k=`${r.station}|${r.product}`;const v=(m.get(k)||0)+r.grossRevenue;m.set(k,v);max=Math.max(max,v)}let html='<table><thead><tr><th>Station</th>'+products.map(p=>`<th>${esc(p)}</th>`).join('')+'<th>Total</th></tr></thead><tbody>';for(const st of stations){let total=0;html+=`<tr><td><strong>${esc(st)}</strong></td>`;for(const p of products){const v=m.get(`${st}|${p}`)||0;total+=v;const alpha=.22+(v/max)*.78;html+=`<td><span class="heat" style="background:rgba(65,230,167,${alpha});padding:8px 10px;display:inline-block">${v?money(v):'—'}</span></td>`}html+=`<td><strong>${money(total)}</strong></td></tr>`}html+='</tbody></table>';$('#matrix').innerHTML=html;}
function renderTable(){const rows=filteredRows();$('#table-body').innerHTML=rows.map(r=>`<tr><td>${esc(r.date)}</td><td>${esc(r.station)}</td><td>${esc(r.product)}</td><td>${num(r.qty)}</td><td>${money(r.grossRevenue)}</td><td>${report.currency} ${(r.grossRevenue/(r.qty||1)).toFixed(2)}</td></tr>`).join('')||'<tr><td colspan="6">No matching rows.</td></tr>';}
function renderCharts(){const rows=filteredRows();renderCards(rows);dateChart($('#date-chart'),groupDate(rows));barChart($('#station-chart'),group(rows,'station'));barChart($('#product-chart'),group(rows,'product'));renderMatrix(rows);renderTable();}
function initFilters(){for(const st of [...new Set(report.rows.map(r=>r.station))].sort()) $('#station-filter').insertAdjacentHTML('beforeend',`<option>${esc(st)}</option>`);for(const pr of [...new Set(report.rows.map(r=>r.product))].sort()) $('#product-filter').insertAdjacentHTML('beforeend',`<option>${esc(pr)}</option>`);$('#station-filter').addEventListener('change',renderCharts);$('#product-filter').addEventListener('change',renderCharts);$('#search').addEventListener('input',renderTable)}
function init(){renderRun();renderCards();renderInsights();initFilters();renderCharts()}
fetch('data/report-data.json').then(r=>{if(!r.ok)throw new Error(`Failed to load report data: ${r.status}`);return r.json()}).then(d=>{report=d;init()}).catch(e=>{document.body.innerHTML=`<main class="section"><h1>Report data failed to load</h1><p>${esc(e.message)}</p></main>`});
