let report;const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];const esc=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));const money=v=>`${report.currency} ${Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2})}`;const pct=v=>`${Number(v||0).toFixed(2)}%`;
function renderRun(){ $('#run-card').innerHTML=`<dl><div><dt>Source workbook</dt><dd>${esc(report.sourceWorkbook)}</dd></div><div><dt>Period</dt><dd>${esc(report.period)}</dd></div><div><dt>Currency</dt><dd>${esc(report.currency)}</dd></div><div><dt>Peak rule</dt><dd>Highest unit price per category</dd></div><div><dt>Output</dt><dd>Raw document + owner follow-up list</dd></div></dl>`}
function renderCards(){const cards=[['Categories checked',report.metrics.categoriesChecked,'Product categories in workbook'],['Peak rows',report.metrics.peakRows,'Rows tied at category peak'],['Premium peaks',report.metrics.categoriesWithPremiumPeak,'Categories where peak > median'],['Rows checked',report.metrics.totalRows,'Total source rows reviewed']];$('#metric-cards').innerHTML=cards.map(c=>`<article class="metric-card"><div class="value">${esc(c[1])}</div><div class="label">${esc(c[0])}</div><div class="detail">${esc(c[2])}</div></article>`).join('')}
function renderStatus(){const c=$('#status-callout'); if(report.metrics.categoriesWithPremiumPeak===0){c.className='callout ok'; c.innerHTML='<strong>No category has a premium peak above its median.</strong> Current data has flat unit pricing inside each category, so all rows in each category tie at the peak price.'}else{c.className='callout warn'; c.innerHTML=`<strong>${report.metrics.categoriesWithPremiumPeak} category/categories have peak price above median.</strong> Start with those category cards and check the listed raw documents.`}}
function renderPeakCards(){ $('#peak-card-grid').innerHTML=report.categoryPeaks.map(p=>`<article class="peak-card"><p class="eyebrow">${esc(p.product)}</p><div class="price">${money(p.peakUnitPrice)}</div><div class="meta">Peak unit price · ${esc(p.peakRowCount)} row(s) tied</div><ul><li>Median: ${money(p.medianUnitPrice)}</li><li>Min: ${money(p.minUnitPrice)}</li><li>Premium vs median: ${pct(p.premiumVsMedianPct)}</li></ul><p class="hint">${esc(p.action)}</p></article>`).join('')}
function barChart(el,data,type){const max=Math.max(...data.map(d=>type==='price'?d.peak:d.peakRows),1);el.innerHTML=data.map(d=>{const val=type==='price'?d.peak:d.peakRows;const text=type==='price'?money(d.peak):`${d.peakRows} row(s)`;return `<div class="bar-row"><div class="bar-label">${esc(d.label)}</div><div class="bar-track"><div class="bar-fill" style="width:${Math.max(3,val/max*100)}%"></div></div><div class="bar-value">${text}</div></div>`}).join('')}
function filteredRows(){const pr=$('#product-filter').value, st=$('#station-filter').value, q=$('#search').value.trim().toLowerCase();return report.peakRows.filter(r=>(pr==='all'||r.product===pr)&&(st==='all'||r.station===st)&&(!q||Object.values(r).join(' ').toLowerCase().includes(q)))}
function renderTable(){const rows=filteredRows();$('#peak-row-body').innerHTML=rows.map(r=>`<tr data-id="${esc(`${r.product}|${r.station}|${r.date}|${r.sourceDocument}`)}"><td><span class="badge">${esc(r.product)}</span></td><td><strong>${money(r.unitPrice)}</strong></td><td>${esc(r.date)}</td><td><strong>${esc(r.station)}</strong><br><span class="hint">${esc(r.investigationParty)}</span></td><td>${Number(r.qty).toLocaleString()}</td><td>${money(r.grossRevenue)}</td><td>${esc(r.sourceDocument)}</td><td>${esc(r.investigationReason)}</td></tr>`).join('')||'<tr><td colspan="8">No peak rows match this filter.</td></tr>'; $$('#peak-row-body tr[data-id]').forEach(tr=>tr.addEventListener('click',()=>showRow(tr.dataset.id)))}
function showRow(id){const [product,station,date,sourceDocument]=id.split('|');const r=report.peakRows.find(x=>x.product===product&&x.station===station&&x.date===date&&x.sourceDocument===sourceDocument);if(!r)return;const p=report.categoryPeaks.find(x=>x.product===r.product);$('#dialog-content').innerHTML=`<p class="eyebrow">Category peak row</p><h2>${esc(r.product)} · ${esc(r.station)} · ${esc(r.date)}</h2><div class="detail-grid"><div class="detail"><div class="k">Peak unit price</div><div class="v">${money(r.unitPrice)}</div></div><div class="detail"><div class="k">Category median</div><div class="v">${money(p?.medianUnitPrice)}</div></div><div class="detail"><div class="k">Premium vs median</div><div class="v">${pct(p?.premiumVsMedianPct)}</div></div><div class="detail"><div class="k">Gross revenue / qty</div><div class="v">${money(r.grossRevenue)} / ${Number(r.qty).toLocaleString()}</div></div><div class="detail"><div class="k">Raw document</div><div class="v">${esc(r.sourceDocument)}</div></div><div class="detail"><div class="k">Investigation party</div><div class="v">${esc(r.investigationParty)}<br>${esc(r.secondaryParty)}</div></div></div><ol>${r.recommendedChecks.map(x=>`<li>${esc(x)}</li>`).join('')}</ol>`;$('#row-dialog').showModal()}
function initFilters(){for(const p of [...new Set(report.peakRows.map(r=>r.product))].sort())$('#product-filter').insertAdjacentHTML('beforeend',`<option>${esc(p)}</option>`);for(const st of [...new Set(report.peakRows.map(r=>r.station))].sort())$('#station-filter').insertAdjacentHTML('beforeend',`<option>${esc(st)}</option>`);['product-filter','station-filter','search'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',renderTable))}
function init(){renderRun();renderCards();renderStatus();renderPeakCards();barChart($('#product-chart'),report.charts.products,'price');barChart($('#station-chart'),report.charts.stations,'rows');$('#workflow-list').innerHTML=report.actionWorkflow.map(x=>`<li>${esc(x)}</li>`).join('');$('#rule-summary').textContent=report.ruleSummary;initFilters();renderTable();$('.close').addEventListener('click',()=>$('#row-dialog').close());$('#row-dialog').addEventListener('click',e=>{if(e.target.id==='row-dialog')e.target.close()})}
fetch('data/report-data.json').then(r=>{if(!r.ok)throw new Error(`Failed to load report data: ${r.status}`);return r.json()}).then(d=>{report=d;init()}).catch(e=>{document.body.innerHTML=`<main class="section"><h1>Report data failed to load</h1><p>${esc(e.message)}</p></main>`});
