let report;const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];const esc=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));const money=v=>`${report.currency} ${Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2})}`;const pct=v=>`${Number(v||0).toFixed(2)}%`;const sevOrder={Critical:0,High:1,Watch:2,Review:3,Normal:4};
function badge(s){return `<span class="badge ${esc(s)}">${esc(s)}</span>`}
function renderRun(){ $('#run-card').innerHTML=`<dl><div><dt>Source workbook</dt><dd>${esc(report.sourceWorkbook)}</dd></div><div><dt>Period</dt><dd>${esc(report.period)}</dd></div><div><dt>Currency</dt><dd>${esc(report.currency)}</dd></div><div><dt>Benchmark method</dt><dd>Product median unit price</dd></div><div><dt>Purpose</dt><dd>Find raw document + party for pricing investigation</dd></div></dl>`}
function renderCards(rows=report.rows){const anom=rows.filter(r=>r.severity!=='Normal');const impact=anom.reduce((s,r)=>s+Math.abs(r.estimatedImpact||0),0);const maxVar=Math.max(0,...rows.map(r=>Math.abs(r.variancePct||0)));const cards=[['Exceptions',anom.length,`${report.metrics.criticalCount} critical · ${report.metrics.highCount} high · ${report.metrics.watchCount} watch`],['Potential impact',money(impact),'Absolute variance impact in current filter'],['Highest variance',pct(maxVar),'Max unit-price variance vs benchmark'],['Rows checked',rows.length,`${report.metrics.totalRows} total workbook rows`]];$('#metric-cards').innerHTML=cards.map(c=>`<article class="metric-card"><div class="value">${esc(c[1])}</div><div class="label">${esc(c[0])}</div><div class="detail">${esc(c[2])}</div></article>`).join('')}
function renderStatus(){const c=$('#status-callout');if(report.metrics.anomalyCount===0){c.className='callout ok';c.innerHTML='<strong>No abnormal pricing detected.</strong> All rows match the product-level benchmark within the current 5% watch threshold. Use the table below as the audit trail for what was checked.'}else{c.className='callout warn';c.innerHTML=`<strong>${report.metrics.anomalyCount} pricing exception(s) found.</strong> Prioritise Critical/High rows, then check the listed raw documents and investigation parties.`}}
function filtered(){const sev=$('#severity-filter').value, st=$('#station-filter').value, q=$('#search').value.trim().toLowerCase();return report.rows.filter(r=>{if(sev==='action'&&r.severity==='Normal')return false;if(!['all','action'].includes(sev)&&r.severity!==sev)return false;if(st!=='all'&&r.station!==st)return false;if(q&&!Object.values(r).join(' ').toLowerCase().includes(q))return false;return true}).sort((a,b)=>(sevOrder[a.severity]-sevOrder[b.severity])||Math.abs(b.variancePct)-Math.abs(a.variancePct))}
function barChart(el,data){const max=Math.max(...data.map(d=>d.anomalies||0),1);el.innerHTML=data.map(d=>`<div class="bar-row"><div class="bar-label">${esc(d.label)}</div><div class="bar-track"><div class="bar-fill" style="width:${Math.max(3,(d.anomalies||0)/max*100)}%"></div></div><div class="bar-value">${d.anomalies} exception(s)</div></div>`).join('')}
function renderCharts(){barChart($('#station-chart'),report.charts.byStation);barChart($('#product-chart'),report.charts.byProduct)}
function renderTable(){const rows=filtered();renderCards(rows);$('#exception-body').innerHTML=rows.map(r=>`<tr data-id="${esc(`${r.date}|${r.station}|${r.product}`)}"><td>${badge(r.severity)}</td><td>${esc(r.date)}</td><td><strong>${esc(r.station)}</strong><br><span class="hint">${esc(r.investigationParty)}</span></td><td>${esc(r.product)}</td><td>${Number(r.qty).toLocaleString()}</td><td>${money(r.unitPrice)}</td><td>${money(r.expectedUnitPrice)}</td><td>${pct(r.variancePct)}</td><td>${esc(r.sourceDocument)}</td><td>${esc(r.reason)}</td></tr>`).join('')||'<tr><td colspan="10">No rows match this filter.</td></tr>'; $$('#exception-body tr[data-id]').forEach(tr=>tr.addEventListener('click',()=>showRow(tr.dataset.id)))}
function showRow(id){const [date,station,product]=id.split('|');const r=report.rows.find(x=>x.date===date&&x.station===station&&x.product===product);if(!r)return;$('#dialog-content').innerHTML=`<p class="eyebrow">${esc(r.severity)} pricing check</p><h2>${esc(r.station)} · ${esc(r.product)} · ${esc(r.date)}</h2><div class="detail-grid"><div class="detail"><div class="k">Unit price</div><div class="v">${money(r.unitPrice)}</div></div><div class="detail"><div class="k">Expected</div><div class="v">${money(r.expectedUnitPrice)}</div></div><div class="detail"><div class="k">Variance</div><div class="v">${pct(r.variancePct)}</div></div><div class="detail"><div class="k">Estimated impact</div><div class="v">${money(r.estimatedImpact)}</div></div><div class="detail"><div class="k">Raw document</div><div class="v">${esc(r.sourceDocument)}</div></div><div class="detail"><div class="k">Investigation party</div><div class="v">${esc(r.investigationParty)}<br>${esc(r.secondaryParty)}</div></div></div><div class="callout"><strong>Reason:</strong> ${esc(r.reason)}</div><ol>${(r.recommendedChecks?.length?r.recommendedChecks:['No pricing exception; no action required.']).map(x=>`<li>${esc(x)}</li>`).join('')}</ol>`;$('#row-dialog').showModal()}
function renderBenchmarks(){ $('#benchmark-grid').innerHTML=report.benchmarks.map(b=>`<article class="metric-card"><div class="value">${money(b.expectedUnitPrice)}</div><div class="label">${esc(b.product)}</div><div class="detail">Samples: ${b.sampleSize} · Range ${money(b.minUnitPrice)}–${money(b.maxUnitPrice)}</div></article>`).join('')}
function initFilters(){for(const st of [...new Set(report.rows.map(r=>r.station))].sort())$('#station-filter').insertAdjacentHTML('beforeend',`<option>${esc(st)}</option>`);['severity-filter','station-filter','search'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',renderTable))}
function init(){renderRun();renderStatus();renderCharts();renderBenchmarks();$('#workflow-list').innerHTML=report.actionWorkflow.map(x=>`<li>${esc(x)}</li>`).join('');$('#rule-summary').textContent=report.ruleSummary;initFilters();renderTable();$('.close').addEventListener('click',()=>$('#row-dialog').close());$('#row-dialog').addEventListener('click',e=>{if(e.target.id==='row-dialog')e.target.close()})}
fetch('data/report-data.json').then(r=>{if(!r.ok)throw new Error(`Failed to load report data: ${r.status}`);return r.json()}).then(d=>{report=d;init()}).catch(e=>{document.body.innerHTML=`<main class="section"><h1>Report data failed to load</h1><p>${esc(e.message)}</p></main>`});
